baseURL = 'https://philiph.dev/'
languageCode = 'en-us'
title = 'PHILIPH.DEV/'

[[menus.main]]
name = 'index.html'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'projects/'
pageRef = '/projects/'
weight = 20

[[menus.main]]
name = 'blog/'
pageRef = '/blog/'
weight = 30

[[menus.main]]
name = 'contact/'
pageRef = '/contact/'
weight = 40
